/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;

import java.awt.Color;
import javax.swing.Icon;

/**
 *
 * @author bth14
 */
public class chatR extends javax.swing.JLayeredPane {

    
    public chatR() {
        initComponents();
        txt.setBackground(new Color(179,233,255));
    }
    
  
       public void setText(String text){
        if(text.equals("")){
            txt.hideText();
        } else{
            txt.setText(text);
        }
        txt.seen();
        
       
        
    }
    public void setImage(Icon...image){
        txt.setImage(true, image);
    
    }
    public void setImage(String...image){
        txt.setImage(false, image);
    
    }
     public void setFile(String fileName,String fileSize){
         txt.setFile(fileName, fileSize);
     }
    public void setTime(){
        txt.setTime("10:30 PM");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt = new components.chat_items();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
        add(txt);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private components.chat_items txt;
    // End of variables declaration//GEN-END:variables
}
