
package components;

import java.awt.Color;
import javax.swing.Icon;

public class chatL_whith_profile extends javax.swing.JLayeredPane {

    
    public chatL_whith_profile() {
        initComponents();
        txt.setBackground(new Color(230,230,230));
    }
    public void setUserProfile(String user){
        txt.setUserProfile(user);
    
        
    }
    public void setImageProfile(Icon image){
    
        Imagepic.setImage(image);
    } 
    
    
    public void setText(String text){
        if(text.equals("")){
            txt.hideText();
        } else{
            txt.setText(text);
        }
        
       
        
    }
    public void setImage(Icon...image){
        txt.setImage(false, image);
    
    }
     public void setImage(String...image){
        txt.setImage(false, image);
    
        
    }
     public void setFile(String fileName,String fileSize){
         txt.setFile(fileName, fileSize);
     }
    public void setTime(){
        txt.setTime("10:30 PM");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        Imagepic = new com.bth.swing.ImageAvatar();
        txt = new components.chat_items();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        Imagepic.setBorderSize(0);
        Imagepic.setImage(new javax.swing.ImageIcon(getClass().getResource("/testingpic/pic1.jpg"))); // NOI18N
        Imagepic.setMaximumSize(new java.awt.Dimension(31, 31));
        Imagepic.setMinimumSize(new java.awt.Dimension(31, 31));

        jLayeredPane1.setLayer(Imagepic, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(Imagepic, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Imagepic, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jLayeredPane1);
        add(txt);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.bth.swing.ImageAvatar Imagepic;
    private javax.swing.JLayeredPane jLayeredPane1;
    private components.chat_items txt;
    // End of variables declaration//GEN-END:variables


}
